CommunityDragon/awesome-league

README.md
I added a Contents header and two new categories as well as adding a couple repositories and links.
=> Adds a Contents header and a couple new links

README.md
This PR adds lol-pick-ban-ui to the list under content creation, may not be the best category but I believed since tournaments are streamed its content creation.
=> Add lol-pick-ban-ui

README.md
Added [Skin Explorer](https://www.skinexplorer.lol) ([GitHub](https://github.com/preyneyv/lol-skin-explorer)), a web-based League of Legends splash art viewer.
=> Added Skin Explorer to README.md

README.md
A GitHub Action for setting up League Client (LCU) on a Windows runner. Enables continuous testing of LCU integration.
=> Added "DevOps Tools" "Setup League Client" and "Download Data Dragon"

README.md
Just add [league-loader](https://github.com/nomi-san/league-loader) - A small plugin loader for League Client, supports CommonJS modules adn DevTools.
=> Add league-loader

README.md
=> removed manaflux's link

README.md
Lytical is like OP.GG for Garena. It provides summoner search and pregame analysis utilizing the League Client API.
URL: https://lytical.app/
GitHub URL: https://github.com/LyticalApp/Lytical
=> Add Lytical

README.md
=> Add "Amumus Friends" to Awesome League

README.md
Disenchanter can no longer handle event tokens so I updated the description to better depict its features.
=> Updated Disenchanter's description

README.md
Just update league-loader after rebranding
=> Add Pengu Loader

README.md
A lightweight program that automatically records LoL games and saves the timestamps of the most important events in the game.
Github URL: https://github.com/FFFFFFFXXXXXXX/league_record
=> Add LeagueRecord

README.md
=> Add Hexgate TS lib

README.md
=> league unglitch

README.md
Suggestion to add ratRequ3ster, a Python GUI App used for interacting with LCU API.
=> Adding ratRequ3ster

README.md
Added Needlework, an explorer and development tool for the LCU. :3
URL: [https://github.com/BlossomiShymae/Needlework](https://github.com/BlossomiShymae/Needlework)
Features include:
- Exploring available endpoints of LCU API with user-interactivity
- Viewing generated auth info
- Examining available data schemas
- Sending HTTP requests to LCU
- Viewer for WebSocket events
=> Add Needlework

README.md
Adds Heimerdinger.lol to the external apps list.
=> add 'heimerdinger.lol' to external apps list

README.md
Added Clean Cuts, a website that provides League of Legends game data in a human-friendly format. :3
URL: [https://blossomishymae.github.io/clean-cuts/](https://blossomishymae.github.io/clean-cuts/)
Repo: [https://github.com/BlossomiShymae/clean-cuts](https://github.com/BlossomiShymae/clean-cuts)
What is viewable:
- Champions
- Items
- Runes
- Summoner icons
- Ward skins
- Summoner emotes
=> Add Clean Cuts

README.md
Added LeagueAutoAccept, a console app that allows you to automatically accept queue, pick or ban a champion and more.
=> Added LeagueAutoAccept

README.md
Replace Needlework with Needlework.Net. It is an improved rewrite of the original tool with the same purpose.
URL: [https://github.com/BlossomiShymae/Needlework.Net](https://github.com/BlossomiShymae/Needlework.Net)
> Features include:
>
> - Exploring available endpoints of LCU API with user-interactivity
> - Viewing generated auth info
> - Examining available data schemas
> - Sending HTTP requests to LCU
> - Viewer for WebSocket events
=> Replace Needlework with Needlework.Net

README.md
Added GrrrLCU, a simple C# wrapper for the LCU. :3
URL: https://github.com/BlossomiShymae/GrrrLCU
Features:
- HTTP support
- WebSocket support using `Websocket.Client` dependency
- Sending WebSocket messages (`EventMessage`) with JSON serialization support
=> Add GrrrLCU

README.md
=> Added lolskin.info

README.md
Added my application (ClutchGG.LOL) to external applications in README.md - Hopefully the right place for it!
=> feat(readme): Add new external application

README.md
A WebApp to watch League of Legend Streams with additonal in-Game Infos from the Riot API such as played Champion, Runes and Elo. Additionally provides an extensive VOD Section where you can search for specific Champions, Roles or Matchups to watch.
=> Added LeagueStreams.gg
